### ISSUE TITLE
Design Note

### ISSUE THREAD

**Issue by AnuthinWongsunkakon** [cadsondemak/Mali#2]
อย่าลืม สรุปรายละเอียดการทำงานประกอบใน Design Note ด้วยนะครับ

**Comment by kitiyapornn** [comment]
รับทราบค่ะ อาจารย์นุ

**Comment by AnuthinWongsunkakon** [comment]
สามารถเทคโน๊ตไว้ในนี้ได้เลยนะครับ โน๊ตของโพรเสจระหว่างทางจะช่วยให้คนที่เข้ามาคอมเม้นท์เข้าใจได้เยอะเลยครับ จะได้ไม่คอมเม้นท์กันซี้ซั้วครับ
