### ISSUE TITLE
ขอคำแนะนำเรื่องแบบนิดนึงค่ะ

### ISSUE THREAD

**Issue by kitiyapornn** [cadsondemak/Mali#3]
ขอคำแนะนำทุกท่านด้วยค่ะว่ามีตรงใหนที่ต้องปรับเปลี่ยนแก้ไข ฝากแนะนำด้วยนะคะ
![mali](https://user-images.githubusercontent.com/35287574/37446069-caf3bdd8-284d-11e8-9239-ce22671e3c94.png)

**Comment by AnuthinWongsunkakon** [comment]
I Think overall is pretty good. Big Improvement from the DEPA original file. Three comments here would be... 

1. Could you please extend the end terminal of  ธ ร ฐ (ปลายจุดจบเส้นที่กระดกแบบปัดออก) I personally think it will be better to make it a little longer so when you expand the weight you still have this detail left to work with. 

2. The knot of ฬ is too small. Make it bigger so it won't close up on you when you do the bolder weight.

3. Also check the size of all the head loops. Make sure that you have somewhat consistency here. From ถ ถึง ต in the screenshot, they seem to have much smaller head loop than  ท น ม บ ป ษ ผ ฝ ฟ พ ห ฬ อ ฮ. I do realize this is a handwriting face and it could be random but the contrast between the smallest and the biggest head loop is a bit too much. I wish you would have more constancy. I think grade 6 students (the original concept of this design) generally have more consistency in their writing than you think.

**Comment by kitiyapornn** [comment]
ขอบคุณสำหรับคำแนะนำค่ะ หลังจากปรับเเบบเเล้วจะมาขอคำแนะนำอีกครั้งนะคะ

**Comment by kitiyapornn** [comment]
![mali](https://user-images.githubusercontent.com/35287574/37778381-68a5a4d2-2e1c-11e8-983d-15c52661fc21.png)

ตอนนี้ได้ปรับแบบตามที่ @AnuthinWongsunkakon แนะนำแล้วค่ะ และได้ทำการเช็ก QA และแก้ไข Report ของ QA เรียบร้อยค่ะ

**Comment by AnuthinWongsunkakon** [comment]
This is pretty good. I like the fact that you have a few of the head loop sizes. You might want to redo the headlamp of  ค ฅ . Especially  ค ฅ they might need to be more round. The head loop of these two characters should be treated the same way as what you did on ศ ต. I have no problem with the Latin. I think it looks pretty good. The rest of Latin 1 will need to be rechecked. Could you please consult with @suppakit- on the mark location for Latin 1. That will be the only concern from me at the moment on the Latin part of this font. Overall, I think it looks pretty good. Would love to see it in a block of text so we can check spacing and etc.

**Comment by kitiyapornn** [comment]
ขอบคุณมากๆค่ะ จะปรับแบบของหัว ค ฅ ตามคำเเนะนำค่ะ
