### ISSUE TITLE
ขอคำแนะนำเรื่องการรวมไฟล์ glyphs เป็น master file

### ISSUE THREAD

**Issue by kitiyapornn** [cadsondemak/Mali#4]
Based on your advice @davelab6 ,let's include the glyphs file into a single file. Now I include the file by taking the Roman and Italic it is included as a single file right here. Or Roman and Italic are should be separate files. please guide me. :D

![master file](https://user-images.githubusercontent.com/35287574/37446641-92ad5d6e-2850-11e8-968c-313ec0b97506.png)

**Comment by AnuthinWongsunkakon** [comment]
In the meanwhile, Could you please consult this with @suppakit- ?

**Comment by suppakit-** [comment]
การรวมไฟล์เป็นไฟล์เดียวแบบนี้ เป็นระเบียบและสะดวกสำหรับการพัฒนาต่อในอนาคต และเป็นสิ่งที่เดฟแนะนำครับ

**Comment by kitiyapornn** [comment]
ขอบคุณค่ะ หนูจะปรึกษา @suppakit- อีกทีนะคะ

**Comment by AnuthinWongsunkakon** [comment]
จริงๆไอเดียน่าจะเป็นเพราะอินแสตนท์เขาไม่ต้องการแยก และคงสะดวกกว่าหากจะเจนเป็นวีฟอนต์ในอนาคตครับ คือถ้าจะใช้เป็นตัวใดตัวนึง ก็เจนอินแสตนท์จากมาสเตอร์เลย ผมยังมองว่ามันน่าจะง่ายกว่าด้วยไม่ต้องมานั่งดูว่าใครหยิบเวทไหนไปแก้ คือไปทีไปทั้งแพคเลยจะเอาอันไหนก็ไปอันแพคเอาเอง น่าจะเป็นอะไรทำนอนนี้นะครับ

**Comment by kitiyapornn** [comment]
ขอบคุณมากค่ะ ที่อธิบายให้ทราบถึงไอเดียของแนวทางการนำไฟล์ไปใช้ และไปพัฒนาต่อในอนาคตค่ะ
